### ISSUE TITLE
[Wayland] not able to resize window and strange cursor on Gnome Wayland

### ISSUE THREAD

**Issue by Mershl** [flathub/io.github.spacingbat3.webcord#96]
https://github.com/flathub/io.github.spacingbat3.webcord/commit/576b5fb38e169ca88e46f3b4b59eb84cfb572fcd enabled Wayland support by default. On Gnome 47 (Wayland session, Fedora 41, AMDGPU) this shows two issues:

- the WebCord window starts rather small and is not resizeableable at any of the four corners or edges
- the cursor is small and pixelated while hovering the WebCord window compared to the default Gnome cursor

I'm not using fractional scaling, or any display scaling for that matter.

**Comment by SpidFightFR** [comment]
> [576b5fb](https://github.com/flathub/io.github.spacingbat3.webcord/commit/576b5fb38e169ca88e46f3b4b59eb84cfb572fcd) enabled Wayland support by default. On Gnome 47 (Wayland session, Fedora 41, AMDGPU) this shows two issues:
> 
>     * the WebCord window starts rather small and is not resizeableable at any of the four corners or edges
> 
>     * the cursor is small and pixelated while hovering the WebCord window compared to the default Gnome cursor
> 
> 
> I'm not using fractional scaling, or any display scaling for that matter.

That's weird, i don't see that issue although i'm seeing another one with the filepicker....
Did you try removing `$HOME/.var/app/io.github.spacingbat3.webcord/config/WebCord/windowState.json` , before reloading the app ?

**Comment by SpidFightFR** [comment]
If that doesn't work try disabling `x11-fallback`, using either the cli or a tool like flatseal, if you're on wayland only ?

**Comment by SpidFightFR** [comment]
> For completeness: disabling the socket `wayland` again (basically reverting the commit) fixes both issues.

By doing that you stick with xwayland instead of a native wayland execution. I wouldn't advise it.

**Comment by Mershl** [comment]
> By doing that you stick with xwayland instead of a native wayland execution. I wouldn't advise it.

I agree, though on Fedora 41 / Gnome 47 WebCord Flatpak is not practically useable while the `wayland` socket is enabled.

**Comment by SpidFightFR** [comment]
> > By doing that you stick with xwayland instead of a native wayland execution. I wouldn't advise it.
> 
> I agree in general, though on Fedora 41 / Gnome 47 WebCord Flatpak is not practically useable while the `wayland` socket is enabled.

I doubt it's a problem caused by wayland, it works nicely on wayland on my side, even with the update.

I'd rather think it's a problem caused by gnome or it's a webcord problem directly. Please make sure webcord has read-only access to your cursors and themes folder.

If that solves the issue then i'll consider adsing those to the flatpak.

**Comment by j20001970** [comment]
> [576b5fb](https://github.com/flathub/io.github.spacingbat3.webcord/commit/576b5fb38e169ca88e46f3b4b59eb84cfb572fcd) enabled Wayland support by default. On Gnome 47 (Wayland session, Fedora 41, AMDGPU) this shows two issues:

Commit author here, can confirm that wayland-native Webcord on Gnome 47 cannot resize window, and cursor size is different from outside of it. I tested wayland Webcord on Plasma and it worked without issue when creating the PR, but didn't test on Gnome.

Can you try copying `/usr/share/icons` to `~/.local/share` and override `--filesystem=xdg-data/icons:ro` and see if cursor appearance can be fixed? That worked for me but window still cannot resize.

**Comment by Mershl** [comment]
> EDIT: Can you try https://github.com/flathub/io.github.spacingbat3.webcord/pull/98 to see whether the cursor problem can be fixed by this?

can confirm, #98 fixes the cursor issue on Fedora 41, Gnome Wayland

**Comment by SpidFightFR** [comment]
https://github.com/flathub/io.github.spacingbat3.webcord/pull/98 merged. It will be up in a few moments.

**Comment by Mershl** [comment]
The window resize issue is not affected by #98. The window cannot be resized and remains its initial size on Gnome Wayland.

**Comment by SpidFightFR** [comment]
> The window resize issue is not affected by #98. The window cannot be resized and remains its initial size on Gnome Wayland.

hard to say that way. Are you able to launch webcord via the terminal, and record the issue please ?
or give us log for that matter ?

**Comment by SpidFightFR** [comment]
At least logs, they are the only way i can help you :sweat_smile:

**Comment by Mershl** [comment]
> Are you able to launch webcord via the terminal, and record the issue please ?

The window edges and corners are not grabable when starting Webcord in Native Wayland mode on Gnome Wayland.
The mouse cursor doesn't turn into the grab icon. clicking and dragging anyway does not show any reaction.

This behaviour was confirmed by @j20001970 as well. KDE Wayland is not affected by this issue. It affects only Gnome Wayland.

```
$ flatpak run io.github.spacingbat3.webcord
[6 zypak-helper] /app/bin/webcord/usr/bin/webcord is not an ELF file
[6 zypak-helper] (it appears to be a shell script?)
[6 zypak-helper] WARNING: supplied target /app/bin/webcord/usr/bin/webcord does not look like a valid Chromium binary!
[6 zypak-helper] Zypak needs to be called directly on the executable *binary*, not any wrappers.
[... waitpid lines removed ...]
[66 zypak-helper] Using spawn strategy test 1 as set by environment
[66:1010/205106.143106:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[116:1010/205106.573957:ERROR:gbm_pixmap_wayland.cc(82)] Cannot create bo with format= YUV_420_BIPLANAR and usage=GPU_READ_CPU_READ_WRITE
[WebSocket] Listening at port 6463.
[UPDATE] Application is up-to-date!
```

**Comment by SpidFightFR** [comment]
> > Are you able to launch webcord via the terminal, and record the issue please ?
> 
> The window edges and corners are not grabable when starting Webcord in Native Wayland mode on Gnome Wayland. The mouse cursor doesn't turn into the grab icon. clicking and dragging anyway does not show any reaction.
> 
> This behaviour was confirmed by @j20001970 as well. KDE Wayland is not affected by this issue. It affects only Gnome Wayland.
> 
> ```
> $ flatpak run io.github.spacingbat3.webcord
> [6 zypak-helper] /app/bin/webcord/usr/bin/webcord is not an ELF file
> [6 zypak-helper] (it appears to be a shell script?)
> [6 zypak-helper] WARNING: supplied target /app/bin/webcord/usr/bin/webcord does not look like a valid Chromium binary!
> [6 zypak-helper] Zypak needs to be called directly on the executable *binary*, not any wrappers.
> [... waitpid lines removed ...]
> [66 zypak-helper] Using spawn strategy test 1 as set by environment
> [66:1010/205106.143106:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
> [116:1010/205106.573957:ERROR:gbm_pixmap_wayland.cc(82)] Cannot create bo with format= YUV_420_BIPLANAR and usage=GPU_READ_CPU_READ_WRITE
> [WebSocket] Listening at port 6463.
> [UPDATE] Application is up-to-date!
> ```

I'm currently trying to search for an answer.
In the meantime, may you try running this command please:
```
flatpak run io.github.spacingbat3.webcord --ignore-gpu-blocklist --enable-features=UseOzonePlatform,VaapiVideoDecoder,WebRTCPipeWireCapturer,smooth-scrolling,gpu-rasterization,zero-copy --ozone-platform=wayland
``` 
(it's the one i use with recommended settings for wayland, it will prolly not resolve your issue but while i search for an answer, it will minimize possible bugs while debugging)

**Comment by SpidFightFR** [comment]
> > Are you able to launch webcord via the terminal, and record the issue please ?
> 
> The window edges and corners are not grabable when starting Webcord in Native Wayland mode on Gnome Wayland. The mouse cursor doesn't turn into the grab icon. clicking and dragging anyway does not show any reaction.
> 
> This behaviour was confirmed by @j20001970 as well. KDE Wayland is not affected by this issue. It affects only Gnome Wayland.
> 
> ```
> $ flatpak run io.github.spacingbat3.webcord
> [6 zypak-helper] /app/bin/webcord/usr/bin/webcord is not an ELF file
> [6 zypak-helper] (it appears to be a shell script?)
> [6 zypak-helper] WARNING: supplied target /app/bin/webcord/usr/bin/webcord does not look like a valid Chromium binary!
> [6 zypak-helper] Zypak needs to be called directly on the executable *binary*, not any wrappers.
> [... waitpid lines removed ...]
> [66 zypak-helper] Using spawn strategy test 1 as set by environment
> [66:1010/205106.143106:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
> [116:1010/205106.573957:ERROR:gbm_pixmap_wayland.cc(82)] Cannot create bo with format= YUV_420_BIPLANAR and usage=GPU_READ_CPU_READ_WRITE
> [WebSocket] Listening at port 6463.
> [UPDATE] Application is up-to-date!
> ```

After looking at your logs, nothing's weird on your side that's for sure.
I need to make sure you indeed disabled both x11 and x11-fallback permissions in flatseal or any tools you use for handling permissions.
If so, may you try uninstalling webcord (you **don't need** to purge the files), then reinstalling the test branch i currently use here:

```
flatpak install --user https://dl.flathub.org/build-repo/135881/io.github.spacingbat3.webcord.flatpakref
``` 
I noticed weird behaviors on the latest release of webcord, upstream is aware of it, the latest release should work but it would be a neat way to test if it's a release issue.

If not, it can only mean it's related to the `run.sh` script, to which i'll make change if needed.

please keep me in touch.
:v:

**Comment by SpidFightFR** [comment]
Alright last message for today on my side (i'll continue to researches tomorrow).

Here is the link to the previous version of the [run.sh](https://github.com/flathub/io.github.spacingbat3.webcord/blob/065d8114521f1d3c78ccb74f5683fb8e5e23c1f1/vitamins/run.sh) script, which the flatpak uses in order to launch webcord.

It's dirty but try replacing the one located in
`$HOME/.local/share/flatpak/app/io.github.spacingbat3.webcord/<arch>/<branch>/<shasum>/files/bin/run.sh` with the one provided in the link. (after making a backup of the original one, just in case)

If it solves the issue, i'll just put a check for gnome desktops with a fix (more or less dirty depending on what answers i got.

If the original script doesn't work despite all the tests stated above, then i have no other choice, but i can't help you there.

**Comment by Mershl** [comment]
> please keep me in touch.

But of course, thank you for your excellent support @SpidFightFR

> I need to make sure you indeed disabled both x11 and x11-fallback permissions in flatseal or any tools you use for handling permissions.

I reset all changes just to be sure and disabled only `x11` and `x11-fallback` via Flatseal.
The Gnome debugging tools (lg) also confirm that Webcord produces a Wayland native window.
![image](https://github.com/user-attachments/assets/65368564-f003-49a8-bca2-9414a4d91e49)

> flatpak run io.github.spacingbat3.webcord --ignore-gpu-blocklist --enable-features=UseOzonePlatform,VaapiVideoDecoder,WebRTCPipeWireCapturer,smooth-scrolling,gpu-rasterization,zero-copy --ozone-platform=wayland

The resize issue is not affected by the flags. The log does not show additional hints.

> flatpak install --user https://dl.flathub.org/build-repo/135881/io.github.spacingbat3.webcord.flatpakref

```
$ flatpak install --user https://dl.flathub.org/build-repo/135881/io.github.spacingbat3.webcord.flatpakref
$ flatpak run io.github.spacingbat3.webcord//test
[6 zypak-helper] Wait found events, but sd-event found none
[6 zypak-helper] /app/bin/webcord/usr/bin/webcord is not an ELF file
[6 zypak-helper] (it appears to be a shell script?)
[6 zypak-helper] WARNING: supplied target /app/bin/webcord/usr/bin/webcord does not look like a valid Chromium binary!
[6 zypak-helper] Zypak needs to be called directly on the executable *binary*, not any wrappers.
[... waitpid lines removed ...]
[66 zypak-helper] Using spawn strategy test 1 as set by environment
[66:1010/224257.070183:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[116:1010/224257.486718:ERROR:gbm_pixmap_wayland.cc(82)] Cannot create bo with format= YUV_420_BIPLANAR and usage=GPU_READ_CPU_READ_WRITE
[WebSocket] Listening at port 6463.
[UPDATE] New application version is available! (v4.10.1 → v4.10.2)

(webcord:66): libnotify-WARNING **: 22:42:57.724: Running in confined mode, using Portal notifications. Some features and hints won't be supported
[6 preload-host-spawn-strategy] Warning: waitpid override ignores groups
```

The resize issue is not affected by repo build 135881. The log shows some additional lines, see above.

**Comment by SpidFightFR** [comment]
> > please keep me in touch.
> 
> But of course, thank you for your excellent support @SpidFightFR
> 
> > I need to make sure you indeed disabled both x11 and x11-fallback permissions in flatseal or any tools you use for handling permissions.
> 
> I reset all changes just to be sure and disabled only `x11` and `x11-fallback` via Flatseal. The Gnome debugging tools (lg) also confirm that Webcord produces a Wayland native window. ![image](https://private-user-images.githubusercontent.com/520251/375538214-65368564-f003-49a8-bca2-9414a4d91e49.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1OTM1MDAsIm5iZiI6MTcyODU5MzIwMCwicGF0aCI6Ii81MjAyNTEvMzc1NTM4MjE0LTY1MzY4NTY0LWYwMDMtNDlhOC1iY2EyLTk0MTRhNGQ5MWU0OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMFQyMDQ2NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MGE5MzZmMzRkNjcyMDE5MzY2MzZkYThhNzc4MjQ4ZDllODI5YWJiYWM1MzAyZGViNjM2MDgzMDEzOWMwMjFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._UDQiAExFIMhjD4IpVawzmXcxuwob1xkHFuogBD7aQY)
> 
> > flatpak run io.github.spacingbat3.webcord --ignore-gpu-blocklist --enable-features=UseOzonePlatform,VaapiVideoDecoder,WebRTCPipeWireCapturer,smooth-scrolling,gpu-rasterization,zero-copy --ozone-platform=wayland
> 
> The resize issue is not affected by the flags. The log does not show additional hints.
> 
> > flatpak install --user https://dl.flathub.org/build-repo/135881/io.github.spacingbat3.webcord.flatpakref
> 
> ```
> $ flatpak install --user https://dl.flathub.org/build-repo/135881/io.github.spacingbat3.webcord.flatpakref
> $ flatpak run io.github.spacingbat3.webcord//test
> [6 zypak-helper] Wait found events, but sd-event found none
> [6 zypak-helper] /app/bin/webcord/usr/bin/webcord is not an ELF file
> [6 zypak-helper] (it appears to be a shell script?)
> [6 zypak-helper] WARNING: supplied target /app/bin/webcord/usr/bin/webcord does not look like a valid Chromium binary!
> [6 zypak-helper] Zypak needs to be called directly on the executable *binary*, not any wrappers.
> [... waitpid lines removed ...]
> [66 zypak-helper] Using spawn strategy test 1 as set by environment
> [66:1010/224257.070183:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
> [116:1010/224257.486718:ERROR:gbm_pixmap_wayland.cc(82)] Cannot create bo with format= YUV_420_BIPLANAR and usage=GPU_READ_CPU_READ_WRITE
> [WebSocket] Listening at port 6463.
> [UPDATE] New application version is available! (v4.10.1 → v4.10.2)
> 
> (webcord:66): libnotify-WARNING **: 22:42:57.724: Running in confined mode, using Portal notifications. Some features and hints won't be supported
> [6 preload-host-spawn-strategy] Warning: waitpid override ignores groups
> ```
> 
> The resize issue is not affected by repo build 135881. The log shows some additional lines, see above.

Okay thanks for making sure !

Welp, fingers crossed for the run script...!

**Comment by Mershl** [comment]
> Here is the link to the previous version of the [run.sh](https://github.com/flathub/io.github.spacingbat3.webcord/blob/065d8114521f1d3c78ccb74f5683fb8e5e23c1f1/vitamins/run.sh) script, which the flatpak uses in order to launch webcord.
It's dirty but try replacing the one located in
$HOME/.local/share/flatpak/app/io.github.spacingbat3.webcord/<arch>/<branch>/<shasum>/files/bin/run.sh with the one provided in the link. (after making a backup of the original one, just in case)

```
$ cp ~/Downloads/run.sh ~/.local/share/flatpak/app/io.github.spacingbat3.webcord/x86_64/test/dc2bfde5d3ad6974c58ba07a97e8662f5d61c0aead4fc3b0c87fd41055a85ca5/files/bin/run.sh
cp: overwrite '~/.local/share/flatpak/app/io.github.spacingbat3.webcord/x86_64/test/dc2bfde5d3ad6974c58ba07a97e8662f5d61c0aead4fc3b0c87fd41055a85ca5/files/bin/run.sh'? y
$ chmod +x ~/.local/share/flatpak/app/io.github.spacingbat3.webcord/x86_64/test/dc2bfde5d3ad6974c58ba07a97e8662f5d61c0aead4fc3b0c87fd41055a85ca5/files/bin/run.sh
$ flatpak run io.github.spacingbat3.webcord//test
[6 zypak-helper] /app/bin/webcord/usr/bin/webcord is not an ELF file
[6 zypak-helper] (it appears to be a shell script?)
[6 zypak-helper] WARNING: supplied target /app/bin/webcord/usr/bin/webcord does not look like a valid Chromium binary!
[6 zypak-helper] Zypak needs to be called directly on the executable *binary*, not any wrappers.
[66 zypak-helper] Using spawn strategy test 1 as set by environment
[66:1010/224718.364314:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[116:1010/224718.771503:ERROR:gbm_pixmap_wayland.cc(82)] Cannot create bo with format= YUV_420_BIPLANAR and usage=GPU_READ_CPU_READ_WRITE
[WebSocket] Listening at port 6463.
[UPDATE] New application version is available! (v4.10.1 → v4.10.2)

(webcord:66): libnotify-WARNING **: 22:47:19.077: Running in confined mode, using Portal notifications. Some features and hints won't be supported
```

sorry @SpidFightFR. this does not show an effect on the resize issue on Gnome Wayland.

**Comment by SpidFightFR** [comment]
> > Here is the link to the previous version of the [run.sh](https://github.com/flathub/io.github.spacingbat3.webcord/blob/065d8114521f1d3c78ccb74f5683fb8e5e23c1f1/vitamins/run.sh) script, which the flatpak uses in order to launch webcord.
> > It's dirty but try replacing the one located in
> > $HOME/.local/share/flatpak/app/io.github.spacingbat3.webcord////files/bin/run.sh with the one provided in the link. (after making a backup of the original one, just in case)
> 
> ```
> $ cp ~/Downloads/run.sh ~/.local/share/flatpak/app/io.github.spacingbat3.webcord/x86_64/test/dc2bfde5d3ad6974c58ba07a97e8662f5d61c0aead4fc3b0c87fd41055a85ca5/files/bin/run.sh
> cp: overwrite '~/.local/share/flatpak/app/io.github.spacingbat3.webcord/x86_64/test/dc2bfde5d3ad6974c58ba07a97e8662f5d61c0aead4fc3b0c87fd41055a85ca5/files/bin/run.sh'? y
> $ chmod +x ~/.local/share/flatpak/app/io.github.spacingbat3.webcord/x86_64/test/dc2bfde5d3ad6974c58ba07a97e8662f5d61c0aead4fc3b0c87fd41055a85ca5/files/bin/run.sh
> $ flatpak run io.github.spacingbat3.webcord//test
> [6 zypak-helper] /app/bin/webcord/usr/bin/webcord is not an ELF file
> [6 zypak-helper] (it appears to be a shell script?)
> [6 zypak-helper] WARNING: supplied target /app/bin/webcord/usr/bin/webcord does not look like a valid Chromium binary!
> [6 zypak-helper] Zypak needs to be called directly on the executable *binary*, not any wrappers.
> [66 zypak-helper] Using spawn strategy test 1 as set by environment
> [66:1010/224718.364314:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
> [116:1010/224718.771503:ERROR:gbm_pixmap_wayland.cc(82)] Cannot create bo with format= YUV_420_BIPLANAR and usage=GPU_READ_CPU_READ_WRITE
> [WebSocket] Listening at port 6463.
> [UPDATE] New application version is available! (v4.10.1 → v4.10.2)
> 
> (webcord:66): libnotify-WARNING **: 22:47:19.077: Running in confined mode, using Portal notifications. Some features and hints won't be supported
> ```
> 
> sorry @SpidFightFR. this does not show an effect on the resize issue on Gnome Wayland.

dangit, that's crazy...!
try completely purging webcord and re-installing the latest release again, then try again with the script method, please ?
*just in case, if needed:
```
flatpak uninstall --delete-data
```

Right now, it's pretty bad, it means that even with the state of Webcord before the 2 commits (for the version bump and the wayland fix) webcord is broken... :/

**Comment by SpidFightFR** [comment]
Also which version of gnome do you use please ?

**Comment by SpidFightFR** [comment]
If nothing works, try purging webcord (again - sorry) and try up this build please : 
```
flatpak install --user https://dl.flathub.org/build-repo/135875/io.github.spacingbat3.webcord.flatpakref
```
(the build i tried as an attempt to fix another issue i got, but unrelated to yours, it reverts https://github.com/flathub/io.github.spacingbat3.webcord/commit/576b5fb38e169ca88e46f3b4b59eb84cfb572fcd in the built app itself (purging what seems to be the root cause of your issue).

**Comment by Mershl** [comment]
> > > Here is the link to the previous version of the [run.sh](https://github.com/flathub/io.github.spacingbat3.webcord/blob/065d8114521f1d3c78ccb74f5683fb8e5e23c1f1/vitamins/run.sh) script, which the flatpak uses in order to launch webcord.
> > > It's dirty but try replacing the one located in
> > > $HOME/.local/share/flatpak/app/io.github.spacingbat3.webcord////files/bin/run.sh with the one provided in the link. (after making a backup of the original one, just in case)
> > 
> > 
> > ```
> > $ cp ~/Downloads/run.sh ~/.local/share/flatpak/app/io.github.spacingbat3.webcord/x86_64/test/dc2bfde5d3ad6974c58ba07a97e8662f5d61c0aead4fc3b0c87fd41055a85ca5/files/bin/run.sh
> > cp: overwrite '~/.local/share/flatpak/app/io.github.spacingbat3.webcord/x86_64/test/dc2bfde5d3ad6974c58ba07a97e8662f5d61c0aead4fc3b0c87fd41055a85ca5/files/bin/run.sh'? y
> > $ chmod +x ~/.local/share/flatpak/app/io.github.spacingbat3.webcord/x86_64/test/dc2bfde5d3ad6974c58ba07a97e8662f5d61c0aead4fc3b0c87fd41055a85ca5/files/bin/run.sh
> > $ flatpak run io.github.spacingbat3.webcord//test
> > [6 zypak-helper] /app/bin/webcord/usr/bin/webcord is not an ELF file
> > [6 zypak-helper] (it appears to be a shell script?)
> > [6 zypak-helper] WARNING: supplied target /app/bin/webcord/usr/bin/webcord does not look like a valid Chromium binary!
> > [6 zypak-helper] Zypak needs to be called directly on the executable *binary*, not any wrappers.
> > [66 zypak-helper] Using spawn strategy test 1 as set by environment
> > [66:1010/224718.364314:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
> > [116:1010/224718.771503:ERROR:gbm_pixmap_wayland.cc(82)] Cannot create bo with format= YUV_420_BIPLANAR and usage=GPU_READ_CPU_READ_WRITE
> > [WebSocket] Listening at port 6463.
> > [UPDATE] New application version is available! (v4.10.1 → v4.10.2)
> > 
> > (webcord:66): libnotify-WARNING **: 22:47:19.077: Running in confined mode, using Portal notifications. Some features and hints won't be supported
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > sorry @SpidFightFR. this does not show an effect on the resize issue on Gnome Wayland.
> 
> dangit, that's crazy...! try completely purging webcord and re-installing the latest release again, then try again with the script method, please ? *just in case, if needed:
> 
> ```
> flatpak uninstall --delete-data io.github.spacingbat3.webcord
> ```
> 
> Right now, it's pretty bad, it means that even with the state of Webcord before the 2 commits (for the version bump and the wayland fix) webcord is broken... :/

```
$ flatpak remove webcord
Similar installed refs found for ‘webcord’:

   1) app/io.github.spacingbat3.webcord/x86_64/stable (system)
   2) app/io.github.spacingbat3.webcord/x86_64/test (user)
   3) All of the above

Which do you want to use (0 to abort)? [0-3]: 2


        ID                                    Branch         Op
 1. [-] io.github.spacingbat3.webcord         test           r

Uninstall complete.
$ flatpak remove webcord --delete-data
Found installed ref ‘app/io.github.spacingbat3.webcord/x86_64/stable’ (system). Is this correct? [Y/n]: 


        ID                                    Branch         Op
 1. [-] io.github.spacingbat3.webcord         stable         r

Uninstall complete.
Delete data for io.github.spacingbat3.webcord? [y/n]: y
$ flatpak install webcord
        ID                                  Branch       Op      Remote       Download
 1. [✓] io.github.spacingbat3.webcord       stable       i       flathub      101,4 MB / 110,1 MB

Installation complete.
$ sudo cp ~/Downloads/run.sh /var/lib/flatpak/app/io.github.spacingbat3.webcord/x86_64/stable/adce348565ea7f84dd1a74c41608ef7fb47a04eb8048e8f531f069edab6c722f/files/bin/run.sh
$ sudo chmod +x /var/lib/flatpak/app/io.github.spacingbat3.webcord/x86_64/stable/adce348565ea7f84dd1a74c41608ef7fb47a04eb8048e8f531f069edab6c722f/files/bin/run.sh
$ flatpak run io.github.spacingbat3.webcord
[3 zypak-helper] /app/bin/webcord/usr/bin/webcord is not an ELF file
[3 zypak-helper] (it appears to be a shell script?)
[3 zypak-helper] WARNING: supplied target /app/bin/webcord/usr/bin/webcord does not look like a valid Chromium binary!
[3 zypak-helper] Zypak needs to be called directly on the executable *binary*, not any wrappers.
[63 zypak-helper] Using spawn strategy test 1 as set by environment
[63:1010/230123.607459:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[114:1010/230124.039485:ERROR:gbm_pixmap_wayland.cc(82)] Cannot create bo with format= YUV_420_BIPLANAR and usage=GPU_READ_CPU_READ_WRITE
[WebSocket] Listening at port 6463.
[UPDATE] Application is up-to-date!
```
latest flathub webcord + linked run.sh does not affect the Gnome Wayland resize issue.

> Also which version of gnome do you use please ?
Gnome 47.0 (Fedora Workstation 41)

**Comment by Mershl** [comment]
> If nothing works, try purging webcord (again - sorry) and try up this build please :
> 
> ```
> flatpak install --user https://dl.flathub.org/build-repo/135875/io.github.spacingbat3.webcord.flatpakref
> ```
> 
> (the build i tried as an attempt to fix another issue i got, but unrelated to yours, it reverts [576b5fb](https://github.com/flathub/io.github.spacingbat3.webcord/commit/576b5fb38e169ca88e46f3b4b59eb84cfb572fcd) in the built app itself (purging what seems to be the root cause of your issue).

```
$ flatpak install --user https://dl.flathub.org/build-repo/135875/io.github.spacingbat3.webcord.flatpakref
error: No such ref 'app/io.github.spacingbat3.webcord/x86_64/test' in remote webcord-origin
```

**Comment by SpidFightFR** [comment]
> > If nothing works, try purging webcord (again - sorry) and try up this build please :
> > ```
> > flatpak install --user https://dl.flathub.org/build-repo/135875/io.github.spacingbat3.webcord.flatpakref
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > (the build i tried as an attempt to fix another issue i got, but unrelated to yours, it reverts [576b5fb](https://github.com/flathub/io.github.spacingbat3.webcord/commit/576b5fb38e169ca88e46f3b4b59eb84cfb572fcd) in the built app itself (purging what seems to be the root cause of your issue).
> 
> ```
> $ flatpak install --user https://dl.flathub.org/build-repo/135875/io.github.spacingbat3.webcord.flatpakref
> error: No such ref 'app/io.github.spacingbat3.webcord/x86_64/test' in remote webcord-origin
> ```

argh... One second pls :sweat_smile:

**Comment by Mershl** [comment]
```
$ flatpak remove webcord --delete-data
$ flatpak install --user https://dl.flathub.org/build-repo/136481/io.github.spacingbat3.webcord.flatpakref
$ flatpak run --socket=wayland io.github.spacingbat3.webcord//test
[6 zypak-helper] /app/bin/webcord/usr/bin/webcord is not an ELF file
[6 zypak-helper] (it appears to be a shell script?)
[6 zypak-helper] WARNING: supplied target /app/bin/webcord/usr/bin/webcord does not look like a valid Chromium binary!
[6 zypak-helper] Zypak needs to be called directly on the executable *binary*, not any wrappers.
[66 zypak-helper] Using spawn strategy test 1 as set by environment
[66:1010/233324.399337:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[116:1010/233324.823619:ERROR:gbm_pixmap_wayland.cc(82)] Cannot create bo with format= YUV_420_BIPLANAR and usage=GPU_READ_CPU_READ_WRITE
[WebSocket] Listening at port 6463.
[UPDATE] New application version is available! (v4.10.1 → v4.10.2)

(webcord:66): libnotify-WARNING **: 23:33:25.044: Running in confined mode, using Portal notifications. Some features and hints won't be supported
```

Does not show an effect on the resize issue on Gnome Wayland.

This might very well be a Gnome issue. Unfortunately I don't have older Gnome releases than 47 available right now for testing.

**Comment by j20001970** [comment]
If we could reproduce the bug in non-flatpak environment, I think it's better to report this problem upstream to have better discussion.

I tried to run wayland-native webcord with appimage-extracted files directly on Gnome 47 and non-resizeable window problem persists, @Mershl can you try to see if you have the same situation?

**Comment by SpidFightFR** [comment]
> If we could reproduce the bug in non-flatpak environment, I think it's better to report this problem upstream to have better discussion.
> 
> I tried to run wayland-native webcord with appimage-extracted files directly on Gnome 47 and non-resizeable window problem persists, @Mershl can you try to see if you have the same situation?

currently that's what makes the most sense to me.
I observed that webcord doesn't register the "gabbing" mechanism, i guess it's a WM issue, if i had to guess, it would be linked to Mutter or something.

**Comment by Mershl** [comment]
Sorry for the delay. non-flatpak Webcord launched with `--ignore-gpu-blocklist --enable-features=UseOzonePlatform,VaapiVideoDecoder,WebRTCPipeWireCapturer,smooth-scrolling,gpu-rasterization,zero-copy --ozone-platform=wayland` on Gnome 47 Wayland does not show the cursor issue, but the resize issue is identical to flatpak Webcord.

**Comment by SpidFightFR** [comment]
> Sorry for the delay. non-flatpak Webcord launched with `--ignore-gpu-blocklist --enable-features=UseOzonePlatform,VaapiVideoDecoder,WebRTCPipeWireCapturer,smooth-scrolling,gpu-rasterization,zero-copy --ozone-platform=wayland` on Gnome 47 Wayland does not show the cursor issue, but the resize issue is identical to flatpak Webcord.

the cursor issue wasn't fixed on flatpak by https://github.com/flathub/io.github.spacingbat3.webcord/pull/98 ?

**Comment by SpidFightFR** [comment]
As for the resizing issue, if it's reproducible on a non-flatpak install, then it's either an upstream webcord issue, or a gnome (mutter) issue...

**Comment by Mershl** [comment]
> > Sorry for the delay. non-flatpak Webcord launched with `--ignore-gpu-blocklist --enable-features=UseOzonePlatform,VaapiVideoDecoder,WebRTCPipeWireCapturer,smooth-scrolling,gpu-rasterization,zero-copy --ozone-platform=wayland` on Gnome 47 Wayland does not show the cursor issue, but the resize issue is identical to flatpak Webcord.
> 
> the cursor issue wasn't fixed on flatpak by #98 ?

The cursor issue was fixed by #98 for flatpak Webcord, and is not present to begin with in non-flatpak Webcord.

**Comment by SpidFightFR** [comment]
> > > Sorry for the delay. non-flatpak Webcord launched with `--ignore-gpu-blocklist --enable-features=UseOzonePlatform,VaapiVideoDecoder,WebRTCPipeWireCapturer,smooth-scrolling,gpu-rasterization,zero-copy --ozone-platform=wayland` on Gnome 47 Wayland does not show the cursor issue, but the resize issue is identical to flatpak Webcord.
> > 
> > 
> > the cursor issue wasn't fixed on flatpak by #98 ?
> 
> The cursor issue was fixed by #98 for flatpak Webcord, and is not present to begin with in non-flatpak Webcord.

Alright... Welp... I think you should make an issue on [Gnome's gitlab - prolly on the mutter side](https://gitlab.gnome.org/GNOME/mutter), since it's related to window management. I would say it's there that people will be able to help you best.

If there's anything i can do to help you more, if people over there ask to tweak permissions or something, please tell us !

take care.
:v:

**Comment by Mershl** [comment]
Feedback from GNOME issue tracker: https://gitlab.gnome.org/GNOME/mutter/-/issues/3754#note_2254327

All wayland compositors without server side decorations seem to hit this issue. This will most likely need to be fixed on electron side.

**Comment by SpidFightFR** [comment]
> Feedback from GNOME issue tracker: https://gitlab.gnome.org/GNOME/mutter/-/issues/3754#note_2254327
> 
> All wayland compositors without server side decorations seem to hit this issue. This will most likely need to be fixed on electron side.

I guess the electron version used is glitched cuz there's also a problem with portals on flatpak (un-noticable on gnome since, the problem is that electron uses GTK filepicker, so gnome's filepicker, ALL THE TIME, even on kde).

Refs:
- https://github.com/SpacingBat3/WebCord/issues/566
- https://github.com/electron/electron/issues/43819

**Comment by EmptyVisual** [comment]
The issue is with Electron specifically. Electron v32 introduced an issue with resizing while running on the wayland backend (does not affect apps running in xwayland) which is also still present in current stable v33 and development builds of Electron. See issues below

The resize issue
https://github.com/electron/electron/issues/44543#issuecomment-2461148285

Reverting to to v31 to use the wayland backend is not an option either, as it suffers from the CSD border issue
https://github.com/electron/electron/issues/42894#issuecomment-2458644654
